repos:
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Custom security validation hook
  - repo: local
    hooks:
      - id: validate-no-sensitive-data
        name: Validate no sensitive AWS data is being committed
        entry: python3
        language: system
        files: \.(yaml|yml|md|py|json)$
        exclude: ^(config\.example\.yaml|reports/example_validation_report\.md)$
        pass_filenames: false
        args: [./scripts/validate_sensitive_data.py]

  # Python-specific hooks
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]
