site_name: EKS Cluster Validator
site_description: Comprehensive validation tool for AWS EKS clusters
site_author: Techize
site_url: https://techize.github.io/eks_validator/

repo_name: techize/eks_validator
repo_url: https://github.com/techize/eks_validator
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2024 Techize

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-committers:
      repository: techize/eks_validator
      branch: main

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: "!!python/name:material.extensions.emoji.to_svg"
      emoji_index: "!!python/name:material.extensions.emoji.twemoji"
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: techize
      repo: eks_validator
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: "!!python/name:pymdownx.superfences.fence_code_format"
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: "!!python/object/apply:pymdownx.slugs.slugify"
      kwds:
        case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
      - Quick Start: getting-started/quick-start.md
  - User Guide:
      - Basic Usage: user-guide/basic-usage.md
      - Advanced Features: user-guide/advanced-features.md
      - Configuration Options: user-guide/configuration.md
      - Troubleshooting: user-guide/troubleshooting.md
  - API Reference:
      - Overview: api/index.md
      - Core Module: api/core.md
      - Configuration: api/config.md
      - Validators: api/validators.md
  - Development:
      - Contributing: development/contributing.md
      - Architecture: development/architecture.md
      - Testing: development/testing.md
  - Changelog: changelog.md
  - About:
      - License: about/license.md
      - Security: about/security.md
