name: Dependency Updates

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
    inputs:
      update_type:
        description: 'Type of update to perform'
        required: true
        default: 'security'
        type: choice
        options:
        - security
        - all

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools

    - name: Update security dependencies
      if: github.event.inputs.update_type == 'security' || github.event_name == 'schedule'
      run: |
        pip-compile --upgrade --resolver=backtracking --generate-hashes requirements.in
        pip-compile --upgrade --resolver=backtracking --generate-hashes requirements-dev.in

    - name: Update all dependencies
      if: github.event.inputs.update_type == 'all'
      run: |
        pip-compile --upgrade --resolver=backtracking --generate-hashes requirements.in
        pip-compile --upgrade --resolver=backtracking --generate-hashes requirements-dev.in

    - name: Run tests with updated dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        python test_basic.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: |
          chore: update dependencies

          - Updated ${{ github.event.inputs.update_type || 'security' }} dependencies
          - All tests pass with updated dependencies
        title: 'chore: update ${{ github.event.inputs.update_type || ''security'' }} dependencies'
        body: |
          ## Dependency Updates

          This PR updates ${{ github.event.inputs.update_type || 'security' }} dependencies using pip-tools.

          ### Changes
          - Updated dependency versions in requirements.txt and requirements-dev.txt
          - All existing tests continue to pass

          ### Testing
          - ✅ Basic functionality tests pass
          - ✅ Pre-commit hooks pass
          - ✅ Code quality checks pass

          ### Review Checklist
          - [ ] Review dependency changes for breaking changes
          - [ ] Test critical functionality manually
          - [ ] Verify no security vulnerabilities introduced
        branch: automated/dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
